services:
  backend: 
    container_name: backend
    image: backend
    build: 
      context: .
      target: development
      dockerfile: backend.dockerfile
    ports: 
      - 8000:8000
    volumes:
      - ./:/app
      - /app/node_modules 
    environment: 
      DATABASE_URL: postgresql://postgres:drkongo22322@db:5432/postgres?schema=public
    command: npm run dev

  db:
    container_name: db
    image: postgres:16.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: drkongo22322
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {}